baseURL = 'https://tunalinux.org'
languageCode = 'en-us'
title = 'Kernel Hacking(7)'
theme = 'tuna'

[markup.highlight]
    lineNoStart = 0
    lineNos = true
    tabWidth = 4
    noClasses = false
    codeFences = true


[menu]
    [[menu.main]]
        identifier = "guides(7)"
        name = "guides(7)"
        url = "/guides/"
        weight = 1
    [[menu.main]]
        identifier = "projects(3)"
        name = "projects(3)"
        url = "/projects/"
        weight = 2
    [[menu.main]]
        identifier = "tks(9)"
        name = "tks(9)"
        url = "/tks/"
        weight = 3

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]
    [markup.tableOfContents]
        startLevel = 2
        endLevel   = 3
        ordered    = true

[privacy]
    [privacy.vimeo]
        disabled = false
        simple   = true
    [privacy.twitter]
        disabled  = false
        enableDNT = true
        simple    = true
    [privacy.instagram]
        disabled = false
        simple   = true
    [privacy.youtube]
        disabled        = false
        privacyEnhanced = true

[services]
    [services.instagram]
        disableInlineCSS = true
    [services.twitter]
        disableInlineCSS = true
